### ISSUE TITLE
CSW22 support

### ISSUE THREAD

**Issue by Ekansh27** [pohara60/dart-scrabble#1]
Hello! I was wondering if you plan on including a CSW22 dictionary support to this API? 

I have the CSW22.txt file, happy to share if need be.

**Comment by pohara60** [comment]
Hi! I looked for donwloads of CSW22, and did not find it. I saw this comment on reddit: "I think its copywrited and so illegal to post." As it is copyright, I cannot include it in this public repository. As you have the file you could clone the repository and modify the project to build it with your file. The modifications are straightforward:

1. Add your CSW22.txt in the lib directory
2. Run the builder as described in the README.md: ```dart run build_runner build```
3. Edit scrabble.dart to change the file in: ```part 'sowpods.dart';``` to the new generated file ```CSW22.dart```.

Good luck!

**Comment by Ekansh27** [comment]
Thank you!
